name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.4', '2.5', '2.6', '2.7', '3.0']
        rubocop: ['0.63.1', '0.81.0', '0.84.0', '0.85.0', '0.86.0', '0.87.0', '1.0.0', '1.x']
      fail-fast: false
    env:
      BUNDLE_GEMFILE: gemfiles/rubocop_${{ matrix.rubocop }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: rake spec
      run: |
        bundle exec rake spec
